name: Coleta Automatica de Clima

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # Bot√£o manual para testes

jobs:
  coleta:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Dependencias
        run: pip install -r requirements.txt

      - name: Rodar Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python coletor_poo.py
